### ISSUE TITLE
Caching builtins -- implement various enhancements

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#13]
## Tasks

* [x]  implement key hashing;
* [x]  implement "load-or-build" functions;
* [x]  implement expiration marker;
* [x]  implement integrity hash;
* [x]  implement cache cleaning of all namespaces;
* [x]  implement cache pruning of expired values;
* [x]  implement cache pruning if out-of-space;
* [x]  implement "default" values for various `cache-open` arguments;  (i.e. `#f` -- no-set;  `#t` -- default, `x` -- that value;)
* [x]  add time-to-live argument to `select`, `include`, and related;
* [x]  implement caching of opened LMDB databases corresponding to previously used namespaces;
* [x]  implement "keyed" caches (used as cache buster or additional axis in addition to namespaces);
* [x]  implement "cache busting" based on a "token", per individual `select`, `include`, and related builtins;  (this could be used to implement something similar to `E-Tag` HTTP header;)
