### ISSUE TITLE
Hash builtins -- implement initial functionality

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#14]
## Tasks

* [x]  implement integer-based hashing (SipHash and SeaHash);
* [x]  implement cryptographic hashing (Blake2b and Blake2s);
* [x]  implement both seeded (explicitly or randomly) and unseeded variants;
* [x]  implement primitive procedures to expose builtins;
