### ISSUE TITLE
Functional builtins -- implement various enhancements

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#17]
## Tasks

* [x]  implement functional composition that allows for multiple values as inputs / outputs;
* [x]  fix implementation of `apply`;  (check R7RS specification;)
* [x]  implement the following function call builtins (and related):
  * [x]  `call-with-list`;
  * [x]  `call-with-vector`;
  * [x]  `call-with-values`;  (part of R7RS;)
