### ISSUE TITLE
Port builtins -- implement value writing

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#18]
## Tasks

* [ ]  implement support for regular expressions;
* [ ]  implement support for uniques;
* [ ]  add flag to accept only values that can be read back (i.e. accepted by the current parser, and compliant with the serialization library);
