### ISSUE TITLE
Configure continuous integration

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#2]
## Tasks

* [x]  identify appropriate continuous integration solutions (that are free, work with Rust nightly, and integrate with Github);
* [x]  choose one of the continuous integration solutions;
* [x]  configure the chosen continuous integration solution;
