### ISSUE TITLE
Enhance `fail_unimplemented!` and `fail_unsupported!` macro to track GitHub issues

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#33]
## Tasks

* [x]  enhance macro to add tracking facility;
* [x]  enhance macro to fail in release mode if tracking information is not filled;
* [x]  update code to use tracking facility;

----

One can use the following regular expression to search places eligible for issue tracking:
```
(fail|failed)(|_unimplemented|_unreachable|_panic|_or_panic)!
```
