### ISSUE TITLE
Process builtins -- implement `exec` functionality

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#61]
## Tasks

* [x]  add builtin function (creating the `Error::Exec` variant);  (mirroring `process-spawn` and related;)
* [x]  add primitives and export them into the context;
* [x]  update `Error` to contain an "arm" for `Exec` (just like `Exit`);
* [x]  update the interpreter to apply the `exec` sys-call;

## Notes

Executing is implemented in a similar fashion to `exit`, in order to allow the evaluator and other components to properly deinitialize their internal state.  Moreover it offers the possibility of "blocking" the execution of the process (like for example in `eval`).
