### ISSUE TITLE
Array builtins -- implement various enhancements

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#62]
## Tasks

* [x]  implement `vector-append!` (similar to `vector-append` but extends a given vector);
* [x]  enhance `vector-push!` to accept multiple values;
* [x]  implement `vector-push-from!` to accept multiple values;
* [x]  enhance `vector-pop!` to return multiple values;
* [x]  enhance `vector-insert!` to accept multiple values;
* [x]  implement `vector-insert-from!` to accept multiple values;
* [x]  enhance `vector-remove!` to allow removing multiple values;
* [x]  implement `vector-resize-at` to allow inserting a range at a given index;
* [x]  implement `vector-clear-at` to allow removing a range at a given index;
* [x]  implement `vector-find` (similar to `find` list builtin);
