### ISSUE TITLE
Port builtins -- implement various UNIX-specific functionality

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#64]
## Tasks

* [x]  `port-descriptor`;
* [x]  `port-descriptor-clone`;
* [x]  `port-descriptor-ref`;
* [x]  `port-descriptor-path`;
* [x]  `port-descriptor-flag-ref` and `port-descriptor-flag-set!`;
  * [x]  `close-on-exec`;
