### ISSUE TITLE
Transcript builtins -- implement activation level configuration

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#65]
## Tasks

* [ ]  implement "internal" transcript activation level configuration (i.e. the compiler, interpreter, etc.);
* [ ]  implement "script" transcript activation level configuration (i.e. the user-code);

----

## Notes

In both cases the configuration should be done either:
* at compile time (via `cfg!` macro);
* at run-time via command-line arguments;
* at run-time via environment variables;
  * [ ]  `VONUVOLI_SCHEME_TRANSCRIPT_LEVEL` for the interpreter;
  * [x]  `VONUVOLI_SCHEME_SCRIPT_TRANSCRIPT_LEVEL` for the script;
