### ISSUE TITLE
Pair, array, bytes, string and record builtins -- enhance all "constructor" functions to allow specifying the resulting's object mutability

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#68]
## Tasks

* [x]  update all direct callers for:
  * [x]  `pair_new`;
  * [x]  `array_new`;
  * [x]  `string_new`;
  * [x]  `bytes_new`;
  * [x]  `record_new`;
  * [x]  `serde_*`;

* [x]  update all primitives to pass an `use-default` as the default mutability:
  * [x]  pairs;
  * [x]  arrays;
  * [x]  strings;
  * [x]  bytes;
  * [x]  records;

* [ ]  implement new (or adapt existing) primitives that allow to explicitly state the mutability:
  * [ ]  pairs;
    * [x]  `make-pair`;
    * [x]  `make-list`;
    * ...
  * [ ]  arrays;
    * [x]  `make-vector`;
    * ...
  * [ ]  strings;
    * [x]  `make-string`;
    * ...
  * [ ]  bytes;
    * [x]  `make-bytevector`;
    * ...
  * [ ]  records;
    * ...
