### ISSUE TITLE
Transcript builtins -- add support for `TranscriptError`, refactor `TranscriptOutputable`

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#73]
## Tasks

* [ ]  introduce `TranscriptError`
* [ ]  rename `TranscriptOutputable` to `TranscriptMessage`;
* [ ]  refactor function signatures;
* [ ]  implement `TranscriptError` for:
  * [ ]  `Error`;
  * [ ]  `ParseError`;
  * [ ]  `std::io::Error`;
  * [ ]  `std::string::String`;
* [ ]  update error formatting to include codes (if available);
* [ ]  update error formatting to exclude debug printing of error;
