### ISSUE TITLE
Runtime builtins -- implement "unique tokens" for build-time, run-time and boot-time

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#75]
## Tasks

* [ ]  add runtime variables for:
  * [ ]  build-time token;  (i.e. the same for the same build, but different for each build;)
  * [ ]  run-time token;  (i.e. the same for the same execution, but different for each execution;)
  * [ ]  boot-time token;  (i.e. on Linux use `/proc/sys/kernel/random/boot_id`;)
* [ ]  expose them as builtins;
