### ISSUE TITLE
Refactor generic functions to use newly introduced Rust `impl Trait` arguments

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#81]
## Tasks

* [x]  replace `&[&Value]` with `&[impl AsRef<Value>]`;
* [ ]  refactor into a single const `INPUTS_EMPTY`;
* [ ]  refactor usage of `vec_vec_to_ref` (and related);
* [ ]  refactor comparison builtins to use `impl Trait`;
