### ISSUE TITLE
Update tracing of errors in evaluator, compiler and optimizer, so that they can be suppressed

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#83]
## Tasks

* [x]  add conditional compilation support for tracing:
  * [x]  evaluator;
  * [x]  compiler;
  * [x]  optimizer;
  * [x]  parser;
* [x]  add dynamic support for tracing to:
  * [x]  evaluator;
  * [x]  compiler;
  * [x]  optimizer;
  * [x]  parser;
* [x]  enable error tracing suppression if evaluation happens in a "guared" environment;
