### ISSUE TITLE
Runtime builtins -- implement sleep (and related functionality)

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#84]
## Tasks

* [x]  implement `(pause <time> [<randomize>])`;
* [ ]  implement `(pause-retry <retry> [<pause-slice>] [<pause-slice-max>] [<pause-exponent-base>] [<randomize>])`;
* [ ]  implement `(retry <thunk> [<max-retries>] [<pause-slice>] [<pause-slice-max>] [<pause-exponent-base>] [<randomize>])`

## Links

* https://en.wikipedia.org/wiki/Exponential_backoff
* https://cloud.google.com/storage/docs/exponential-backoff
* https://developers.google.com/api-client-library/java/google-http-java-client/backoff
* https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
