### ISSUE TITLE
Parser -- enhance error reporting of parsing errors

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#89]
## Tasks

* [ ]  add line-numbers in transcript output;
* [ ]  highlight line in transcript output;
* [ ]  show only a few lines of the source code in the transcript output;
