### ISSUE TITLE
Value builtins -- implement `*-swap!` functionality for various values

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#94]
## Tasks

* implement variants:
  * [ ]  `(*-swap! left right)`
  * [ ]  `(*-swap! left left-start right)`
  * [ ]  `(*-swap! left left-start right right-start)`
  * [ ]  `(*-swap! left left-start right right-start right-end)`
* implement for:
  * [ ]  arrays;
  * [ ]  lists;
  * [ ]  strings;
  * [ ]  bytes;
