### ISSUE TITLE
Use `clippy` to "lint" the code base

### ISSUE THREAD

**Issue by cipriancraciun** [volution/vonuvoli-scheme#96]
## Tasks

* [x]  handle lints from `clippy` category;
* [x]  handle lints from `clippy_pedantic` category;
* [x]  handle lints from `clippy_complexity` category;
* [x]  handle lints from `clippy_correction` category;
* [x]  handle lints from `clippy_restriction` category;
* [x]  handle lints from `clippy_perf` category;
* [x]  handle lints from `clippy_style` category;
* [x]  handle lints from `clippy_nursery` category;
